# Bag of Words and TF-IDF
Below, we'll look at three useful methods of vectorizing text.
- `CountVectorizer` - Bag of Words
- `TfidfTransformer` - TF-IDF values
- `TfidfVectorizer` - Bag of Words AND TF-IDF values

Let's first use an example from earlier and apply the text processing steps we saw in this lesson.

In [1]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [2]:
corpus = ["The first time you see The Second Renaissance it may look boring.",
        "Look at it at least twice and definitely watch part 2.",
        "It will change your view of the matrix.",
        "Are the human people the ones who started the war?",
        "Is AI a bad thing ?"]

In [3]:
stop_words = stopwords.words("english")
lemmatizer = WordNetLemmatizer()

Use the skills you learned so far to create a function `tokenize` that takes in a string of text and applies the following:
- case normalization (convert to all lowercase)
- punctuation removal
- tokenization, lemmatization, and stop word removal using `nltk`

Feel free to refer back to previous sections to complete these steps!

In [4]:
def tokenize(text):
    # normalize case and remove punctuation
    text = re.sub(r"[^a-zA-Z0-9]", " ", text.lower())
    
    # tokenize text
    tokens = word_tokenize(text)
    stop_words = [w for w in tokens if w not in stopwords.words('english')]
    
    # lemmatize andremove stop words
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]

    return tokens

# `CountVectorizer` (Bag of Words)

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

# initialize count vectorizer object
vect = CountVectorizer(tokenizer=tokenize)

In [6]:
# get counts of each token (word) in text data
X = vect.fit_transform(corpus)

In [7]:
# convert sparse matrix to numpy array to view
X.toarray()

array([[0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 1, 0],
       [0, 1, 0, 2, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 0, 0, 3, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [8]:
# view token vocabulary and counts
vect.vocabulary_

{'the': 7,
 'you': 10,
 'it': 5,
 'at': 3,
 'and': 1,
 'will': 9,
 'your': 11,
 'of': 6,
 'are': 2,
 'who': 8,
 'is': 4,
 'a': 0}

# `TfidfTransformer`

In [9]:
from sklearn.feature_extraction.text import TfidfTransformer

# initialize tf-idf transformer object
transformer = TfidfTransformer(smooth_idf=False)

In [10]:
# use counts from count vectorizer results to compute tf-idf values
tfidf = transformer.fit_transform(X)

In [11]:
# convert sparse matrix to numpy array to view
tfidf.toarray()

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.35392781,  0.        ,  0.70785563,  0.        ,  0.        ,
         0.61129004,  0.        ],
       [ 0.        ,  0.43293598,  0.        ,  0.86587196,  0.        ,
         0.25066348,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.30220933,  0.52196393,  0.30220933,  0.        ,  0.52196393,
         0.        ,  0.52196393],
       [ 0.        ,  0.        ,  0.44645466,  0.        ,  0.        ,
         0.        ,  0.        ,  0.77547177,  0.44645466,  0.        ,
         0.        ,  0.        ],
       [ 0.70710678,  0.        ,  0.        ,  0.        ,  0.70710678,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]])

# `TfidfVectorizer`
`TfidfVectorizer` = `CountVectorizer` + `TfidfTransformer`

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

# initialize tf-idf vectorizer object
vectorizer = TfidfVectorizer()

In [13]:
# compute bag of word counts and tf-idf values
X = vectorizer.fit_transform(corpus)

In [14]:
# convert sparse matrix to numpy array to view
X.toarray()

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.30298183,  0.        ,  0.        ,  0.30298183,  0.        ,
         0.        ,  0.20291046,  0.        ,  0.24444384,  0.        ,
         0.30298183,  0.        ,  0.        ,  0.        ,  0.        ,
         0.30298183,  0.30298183,  0.30298183,  0.        ,  0.40582093,
         0.        ,  0.30298183,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.30298183,  0.        ],
       [ 0.        ,  0.30015782,  0.        ,  0.60031564,  0.        ,
         0.        ,  0.        ,  0.30015782,  0.        ,  0.        ,
         0.        ,  0.20101919,  0.30015782,  0.24216544,  0.        ,
         0.        ,  0.        ,  0.        ,  0.30015782,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.30015782,  0.        ,  0.        ,
         0.30015782,  0.        ,  0.        ,  0.